### ISSUE TITLE
LancerEdit.exe crashes when minimized

### ISSUE THREAD

**Issue by IrateRedKite** [Librelancer/Librelancer#105]
This is occurring consistently for me in the Windows stable build, system specs are as follows:

- Windows 10 Home 64-bit (Build 19045)
- AMD Ryzen 7 3700X 8-Core Processor
- NVIDIA GeForce GTX 1060 6GB

```
GL Error: Invalid Framebuffer Operation
   at LibreLancer.GL.ErrorCheck()
   at LancerEdit.MainWindow.Draw(Double elapsed)
   at LibreLancer.Game.Run()
   at LancerEdit.Program.<>c__DisplayClass0_0.<Main>b__0()
   at LibreLancer.AppHandler.Run(Action action, Action onCrash)

Librelancer Version: 2023.02
```

This issue doesn't seem to occur for other utilities like ThnPlayer or InterfaceEdit, only LancerEdit.

**Comment by CallumDev** [comment]
This should be fixed in latest daily build, please confirm

**Comment by IrateRedKite** [comment]
This does indeed appear to be fixed in the latest daily! Cheers for getting this sorted :)
