### ISSUE TITLE
Shadows in "Normals" view on Models are blocking sight

### ISSUE THREAD

**Issue by erikroe** [Librelancer/Librelancer#117]
When viewing models with the "Normals" options, I would expect no shadows to be cast. But they are, and so they cover the colourful surfaces I actually want to inspect.
![grafik](https://github.com/Librelancer/Librelancer/assets/48999656/c1cc8534-bb55-41e4-9f3b-e12914794a3b)

It should rather be flat lit as this:
![grafik](https://github.com/Librelancer/Librelancer/assets/48999656/a1ddd160-562c-42db-87e3-da6014b4a854)

**Comment by CallumDev** [comment]
Normals mode shader has been replaced with one based on this: https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@8.3/manual/writing-shaders-urp-unlit-normals.html
