### ISSUE TITLE
An equivalent project (a project with the same global properties and tools version) is already present in the project collection

### ISSUE THREAD

**Issue by war1644** [Librelancer/Librelancer#12]
hi, 
I follow the README process test, in the running **slngen.bat** error :
> An equivalent project (a project with the same global properties and tools version) is already present in the project collection, with the path "D:\dev\Librelancer\src\LibreLancer\LibreLancer.csproj". To load an equivalent into this project collection, unload this project first.
![image](https://user-images.githubusercontent.com/16129819/34242967-6cca0f4a-e659-11e7-9c95-85c83bdeaaf1.png)

I search for information based on errors, but still do not solve the problem. [stackoverflow](https://stackoverflow.com/questions/34092898/visual-studio-2015-an-equivalent-project-is-already-present-in-the-project-coll) 

what can be prompted me? thanks

**Comment by CallumDev** [comment]
This is probably an issue with my usage of the msbuild API. I’ll push a fix soon.

**Comment by CallumDev** [comment]
还有，你在用什么VS？2015呢？
也可以用英文试试吗？

**Comment by war1644** [comment]
I use VS2017 ^_^;
I pulled the code back and tried it again with the English system, still the wrong 
![image](https://user-images.githubusercontent.com/16129819/34245050-34e52b1e-e663-11e7-9665-bccb2f8b0d07.png)

Look forward to your early repair；
good work!

**Comment by CallumDev** [comment]
This should be fixed in the latest commit. Please pull the changes and run slngen with the /rebuild flag

**Comment by war1644** [comment]
runing lastest slngen, alert error 'FontConfigSharp.csproj not find'.
**I found the folders（\Librelancer\extern\xxxxx） under the path empty.**  emmmmmm,These files are not included in the Git repository.
Helpless, I had to find before VS2017 automatically generated these files copied past.
Run again slngen, and finally succeeded in generating the LibreLancer.Windows.sln.
succeeded!
Thanks for help!!!
