### ISSUE TITLE
LancerEdit not showing cockpit glass texture on some models

### ISSUE THREAD

**Issue by erikroe** [Librelancer/Librelancer#121]
The cockpit glass on any Corsair ship (`SHIPS/PIRATES/.../`) are not being displayed (they use `KUSARI/ku_playerships.mat`) at all.

![grafik](https://github.com/Librelancer/Librelancer/assets/48999656/d97743f6-7645-4a20-a261-c61d0492b271)

Using most recent GIT version.

Operating System: Nobara Linux 37
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.105.0
Qt Version: 5.15.9
Kernel Version: 6.2.14-300.fsync.fc37.x86_64 (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Ryzen 7 5800X3D 8-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: Micro-Star International Co., Ltd
Product Name: MS-7C02
System Version: 1.0
Mesa 23.1.0
RX 7900XTX

**Comment by erikroe** [comment]
[LancerEdit.pi_elite.trace.tar.gz](https://github.com/Librelancer/Librelancer/files/11576828/LancerEdit.pi_elite.trace.tar.gz)

**Comment by CallumDev** [comment]
This is a bug with the Freelancer: HD Edition files.

https://github.com/BC46/freelancer-hd-edition/issues/148
