### ISSUE TITLE
Implement friendly front-end for LLServer

### ISSUE THREAD

**Issue by JimJamJamie** [Librelancer/Librelancer#126]
# LLServer Improvements

I have listed these in a suggested order of priority for implementation due to their importance/usefulness.

### The tragedy of the hidden `--makeconfig`
In the meantime, before the UI is implemented, running LLServer without a config file shows the following message:
`Can't find librelancerserver.config.json`

Please add information about the `--makeconfig` flag in the message as currently this is a human rights violation due to the suffering it causes to noobs.

### Supply a default `librelancerserver.config.json` file so that LLServer will actually run on the first attempt
The above tragedy could also be avoided by supplying a config file with builds, containing default parameters. Not unlike the commented out server settings one can find in `freelancer.ini`.

Please see below for an example config that could be included:
```
{
  "ServerName": "Starflier Universe",
  "ServerDescription": "My cool Librelancer server",
  "FreelancerPath": "C:\\Program Files (x86)\\Microsoft Games\\Freelancer",
  "LoginUrl": null,
  "DatabasePath": "starflier_universe.db",
  "UseLazyLoading": true,
  "Admins": null,
  "Port": 43443
}
```

### Copy & paste the Launcher.exe front end for LLServer
(I realise this is not actually a copy&paste job).

The Launcher UI would be perfectly adequate for setting LLServer launch options (to populate `librelancerserver.config.json`) instead of typing the values into the console during `LLServer --makeconfig`.

This would be a nice stepping stone towards reimplementing the full FLServer UI.

### Default file location for LLServer should be the /librelancer directory, not wherever the script is being executed
`LLServer --makeconfig` will output the librelancerserver.config.json file in the current working directory, which may not be the Librelancer directory.

It may not be worth pursuing this (due to the need to find a cross-platform way to find the path of the running executable, or requiring the user to type the path to where the librelancer directory is) and focusing on the UI instead.

**Comment by CallumDev** [comment]
Notes (for me), combine with #129 - share code around where config and data files should go

**Comment by CallumDev** [comment]
Done in 05379df
