### ISSUE TITLE
LancerEdit: Incorrect texture shown in Model Viewer when having two of the same UTF files loaded with different textures

### ISSUE THREAD

**Issue by BC46** [Librelancer/Librelancer#150]
When loading a UTF file like `prop_glass_green.3db` in LancerEdit and opening the Model Viewer, it displays the object correctly:
![image](https://github.com/Librelancer/Librelancer/assets/45081813/d53d2606-feaf-471b-812c-aa845a7b1823)

However, after loading another `prop_glass_green.3db` with a custom texture and opening the Model Viewer with it, the object is displayed using the texture from the other `prop_glass_green.3db`. Only after unloading the first UTF file and re-opening the Model Viewer on the second file, the custom texture is correctly shown.

It would be nice if in this case the two Model Viewer instances would display the textures from the UTF files that they are supposed to visualize. This way it's easier to compare different textures on the same object.

**Comment by treewyrm** [comment]
It behaves similar to game - whichever comes first is used until it is cache is dropped. Resources embedded into model files have no special priority over those linked externally. Basically you should avoid having same material and texture names for different resources. Give the other one a unique name instead.

**Comment by CallumDev** [comment]
@treewyrm is correct here, LancerEdit functions the same as the main engine/Freelancer by not loading duplicate textures until the old one is dropped. 

It -is- possible codewise to make independent resource contexts, but I am not sure how to best represent this in the UI without breaking the regular workflows. Leaving open for possible ideas/discussion on

A) Warning when you have two of the same resource open
B) Opening UTF files in 2 different resource contexts (maybe coloured tabs)?

**Comment by BC46** [comment]
The main reason I brought this up is because UTF Editor *does* allow two different textures with the same name to be shown simultaneously in the Model Viewer. This makes comparing the different textures more convenient.

**Comment by CallumDev** [comment]
I have added a Detach Resources button to the utf tab in commit [c87781c](https://github.com/Librelancer/Librelancer/commit/c87781c709c3dad543c1de1ddf5164ca0f9fb6f9):

![image](https://github.com/Librelancer/Librelancer/assets/10167247/1afa8358-3745-4609-95ff-5106170e30a0)

Select this before clicking View Model when you are looking at a file that duplicates another model. This gives the tab a highlight colour to indicate it has been detached from the app-shared resource lookups.

Here i've opened a vanilla prop, when the same prop from HD edition is already loaded (and detached).

![image](https://github.com/Librelancer/Librelancer/assets/10167247/eca1aa23-a9b7-4ee7-8e5b-04c8e6c52e7a)

**Comment by erikroe** [comment]
I have come across this problem, too, when looking at Starspheres. The caching of textures held until I closed the entire LancerEdit. Forcing me to restart it each time.
I have entirely not noticed the Detach Resources button. I would, in context of being in an editor, expect this to be default behavior. Not an extra button.
