### ISSUE TITLE
Audio doesn't recover/switch when usb audio device is (un)plugged

### ISSUE THREAD

**Issue by MinoForge** [Librelancer/Librelancer#156]
Two behaviors observed:

1)
- Have a usb headset plugged in, boot `lancer.exe`
- Hear audio in headset
- Unplug headset
- Log starts spamming `[Warning: 13:31:47] Audio: Buffer underrun`, and audio never comes from default speakers
  - Plugging headset back in does not recover audio to headset either.

2)
- Start `lancer.exe` _without_ usb headset plugged in
- Hear audio from speakers
- Plug headset in
- Audio continues playing from speakers, _not_ headset
  - Plugging/unplugging headset has no effect whatsoever.

**Comment by CallumDev** [comment]
From research this is an openal-soft limitation. Issue with possible fix discussion points outlined here: https://github.com/kcat/openal-soft/issues/533

**Comment by CallumDev** [comment]
Implemented in 13b3626 through the `alcReopenDeviceSOFT` openal-soft extension method, as well as getting events through windows IMMNotificationClient, as this bug doesn't seem to affect Linux.

If openal-soft implements a method to check the default audio device change internally, we can move to that later.

**Comment by MinoForge** [comment]
Tested both scenarios from above with that commit(well, with the one right after it that fixes the build number). Working perfectly :)
