### ISSUE TITLE
Improve way of finding SUR files for an opened model

### ISSUE THREAD

**Issue by erikroe** [Librelancer/Librelancer#164]
Opening related SUR files for a model I currently have in 3d viewer is very annoying as of now. It requires me to constantly click around my file hierarchy to find the related files.

Following suggestions:
- for Freelancer at least we know SUR files -must- be same-named and directly next to the model file. So it should be checked first if this file exists and loaded automatically (maybe not displaying it by default)
- the SUR search dialog should always start in the directory the currently viewed model is at, assuming the file is there or very close to it

**Comment by CallumDev** [comment]
I have updated the .sur browser to start at the path of the model. I've opted not to do automatic loads for now, but this should be a big improvement for you
