### ISSUE TITLE
Feature Request: State Graph Editor

### ISSUE THREAD

**Issue by Beaglerush** [Librelancer/Librelancer#177]
I'd love the ability to edit and save state graphs in the LancerEdit state graph viewer, and to add all-new custom state graph entries to the state_graph.db in a similar way (adding whole new "<CUSTOM> (Leader)" and "<CUSTOM> (Escort)" graphs to allow for new AI brains to be used in-game)
@Lazrius has worked with this before and can help and I can also provide my (beginner's!) understanding of how the state graphs work and any other input needed. Thanks and I hope this seems worth a look!

**Comment by CallumDev** [comment]
Implemented in 2bbd7b0
