### ISSUE TITLE
macOS build broken

### ISSUE THREAD

**Issue by CallumDev** [Librelancer/Librelancer#18]
Code is unmaintained. It is possible to clean up the scripts + launcher to make it run though

**Comment by afreuden** [comment]
Hello, I have attempted to build Librelancer on macOS 10.12.6 with dependencies. It reached 93% and exited on `nvttso`

```
[ 93%] Linking CXX shared library ../binaries/libnvtt.dylib
ld: unknown option: --whole-archive
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [binaries/libnvtt.dylib] Error 1
make[1]: *** [nvttso/CMakeFiles/nvttso.dir/all] Error 2
make: *** [all] Error 2
An error occurred when executing task 'BuildNatives'.
Error: One or more errors occurred.
	Make exited with error code 2
```

I am guessing nv is nvidia? I am running an AMD RX580 so unsure if the error is due to this.

Hope this may help with troubleshooting the macOS build. Will follow up if I come across a solution.

**Comment by CallumDev** [comment]
Not an AMD issue, nvtt is just a texture library. The CMakeLists file in src/nvtt_shared needs to be rewritten. However a lot of the build needs to be rewritten as I've removed all the mac dependencies from the build + there are no longer steps to build the application bundle and deal with the dylibs etc. Needs a full maintainer basically.

**Comment by afreuden** [comment]
I did some digging and it appears the macOS version of `ld` does not support `--whole-archive` or `--no-whole-archive`. Looks like that is an exclusively Linux thing. The macOS equivalents are `-all_load` and `-noall_load` respectively. I modified the CMakeLists as such and was able to build Librelancer successfully:

```
cmake_minimum_required (VERSION 2.8.8)
project(nvttso)
set(CMAKE_BUILD_TYPE release)
set(CMAKE_SKIP_BUILD_RPATH true)
add_definitions(-DNV_NO_ASSERT -D'nvCheckMacro\(x\)=\(x\)')
add_subdirectory(../../extern/nvidia-texture-tools nvtt)
add_library(nvttso SHARED main.c)
set_target_properties(nvttso PROPERTIES
	OUTPUT_NAME "nvtt"
)
target_link_libraries(
	nvttso
	-Wl,-all_load nvcore
	nvimage
	nvmath
	nvthread
	squish
	bc6h
	bc7
	rg_etc1
	nvtt -Wl,-noall_load
)
```

**Comment by CallumDev** [comment]
I'll patch CMakeLists.txt for nvtt_shared to work on macOS and Linux to make future porting easier. Someone with an actual mac would have to do the rest of it though, mine died a long time ago.

**Comment by afreuden** [comment]
I think you may need to do an OS check as `ld` for Linux doesn't have `-all_load` and `-noall_load`. I forgot to mention that sorry. I do have a Mac, happy to do some further testing. You mentioned you removed all the code for Mac? Was it present in a past commit?

**Comment by CallumDev** [comment]
The latest commit added an if check. The last commit where mac support was functional was probably 3de1549 from June 2017, may be a bit earlier than that. The latest I'd bother trying is 0018c5f from December 2017. 

Mac support was removed to be able to move a lot of the engine to native C/++ (physics and audio) so the codebase is very very different from back then. This is why it'd need a dedicated mac developer as opposed to tester as a lot of the stuff now is just flat out unimplemented, and I don't have the resources to maintain the mac backend as the codebase evolves. Apple deprecating OpenGL also means it's quite slow and a lot of new features I want to add flat out won't work. The only real option in that case would be to rewrite the entire engine to support multiple backends (including vulkan/metal) which is quite difficult as the FL content is build around legacy features that are annoying to implement.

The challenge is still up for someone a bit insane who wants to take the challenge.

**Comment by CallumDev** [comment]
With notarization being a thing, macOS is now officially out of scope and won't be supported in master.
