### ISSUE TITLE
Throttle controls broken

### ISSUE THREAD

**Issue by CallumDev** [Librelancer/Librelancer#19]
Scroll wheel and Up/Down does not change throttle speed in SpaceGameplay currently.

**Comment by gp-alex** [comment]
i found that w/s strafes up/down currently
and a/d (left-right) strafes are wrong directions (tho in code it is stated as intentional)

**Comment by CallumDev** [comment]
Throttle should be up/down for demo, thanks. I think default FL has throttle on W/S and strafe up and down unmapped.

Strafe code may have been intentional at the time but I think some change means the subtraction is no longer necessary. On to-do list to fix

**Comment by CallumDev** [comment]
This was fixed ages ago, can't remember when but Up/Down do change throttle
