### ISSUE TITLE
Demo support?

### ISSUE THREAD

**Issue by neuromancer** [Librelancer/Librelancer#3]
Freelancer demo seems to be [freely available to download](http://www.fileplanet.com/120389/download/Freelancer-Demo). Can Librelancer support it?

**Comment by CallumDev** [comment]
It should support it since the demo is just a subset of regular Freelancer features. I'll test it at some point, and (hopefully) close the issue if it works.

**Comment by neuromancer** [comment]
Thanks, it will be great since Freelancer is not easy available in steam or other legal websites.

**Comment by neuromancer** [comment]
Any luck trying the demo? If it runs, could be nice to show this project!

**Comment by TheSuspiciousWombat** [comment]
I did built it with monodevelop on archlinux (got a ton of errors with xbuild) and installed the demo via wine.
I got the following error: 
`
System.IO.FileNotFoundException has been thrown
Could not find file "/home/suswombat/.wine/drive_c/Program Files (x86)/Microsoft Games/Freelancer Trial/DATA/INTERFACE/INTRO/IMAGES/startupscreen_1280.tga".`

As i dot have the full version here atm i cant test if it works there so it might be a problem on my side anyways

**Comment by CallumDev** [comment]
This is fixed as of 073c41f
It'll crash if you try to jump to the other systems as I haven't implemented `locked_gate` or any of that goodness yet, but the bits where the data is present will work.
