### ISSUE TITLE
MIT Relicense

### ISSUE THREAD

**Issue by CallumDev** [Librelancer/Librelancer#45]
I'd like to relicense this project to be MIT.

@Giperionn 
@gp-alex 
Please comment here to give permission for your changes to be licensed under MIT.
I've emailed Malte Rupprecht for permission for their code, if that does not turn out fruitful the following files under src need to be rewritten and/or removed. As this is quite core code it may become quite a task:

- ./LibreLancer.Compatibility/Ini/BooleanValue.cs
- ./LibreLancer.Compatibility/Ini/Section.cs
- ./LibreLancer.Compatibility/Ini/IniFile.cs
- ./LibreLancer.Compatibility/Ini/IValue.cs
- ./LibreLancer.Compatibility/Ini/Entry.cs
- ./LibreLancer.Compatibility/Ini/StringValue.cs
- ./LibreLancer.Compatibility/Ini/IniValueType.cs
- ./LibreLancer.Compatibility/Ini/SingleValue.cs
- ./LibreLancer.Compatibility/Ini/Int32Value.cs
- ./LibreLancer.Compatibility/GameData/Characters/Accessory.cs
- ./LibreLancer.Compatibility/GameData/Characters/CostumesIni.cs
- ./LibreLancer.Compatibility/GameData/Characters/Bodypart.cs
- ./LibreLancer.Compatibility/GameData/Characters/Costume.cs
- ./LibreLancer.Compatibility/GameData/Characters/BodypartsIni.cs
- ./LibreLancer.Compatibility/GameData/MouseIni.cs
- ./LibreLancer.Compatibility/GameData/Solar/WeaponsPlatform.cs
- ./LibreLancer.Compatibility/GameData/Solar/JumpGate.cs
- ./LibreLancer.Compatibility/GameData/Solar/Waypoint.cs
- ./LibreLancer.Compatibility/GameData/Solar/SolararchIni.cs
- ./LibreLancer.Compatibility/GameData/Solar/Loadout.cs
- ./LibreLancer.Compatibility/GameData/Solar/MissionSatellite.cs
- ./LibreLancer.Compatibility/GameData/Solar/NonTargetable.cs
- ./LibreLancer.Compatibility/GameData/Solar/LoadoutsIni.cs
- ./LibreLancer.Compatibility/GameData/Solar/DockingRing.cs
- ./LibreLancer.Compatibility/GameData/Solar/Star.cs
- ./LibreLancer.Compatibility/GameData/Solar/TradelaneRing.cs
- ./LibreLancer.Compatibility/GameData/Solar/Station.cs
- ./LibreLancer.Compatibility/GameData/Solar/Sun.cs
- ./LibreLancer.Compatibility/GameData/Solar/StararchIni.cs
- ./LibreLancer.Compatibility/GameData/Solar/DestroyableDepot.cs
- ./LibreLancer.Compatibility/GameData/Solar/JumpHole.cs
- ./LibreLancer.Compatibility/GameData/Solar/Planet.cs
- ./LibreLancer.Compatibility/GameData/Solar/Satellite.cs
- ./LibreLancer.Compatibility/GameData/Solar/AirlockGate.cs
- ./LibreLancer.Compatibility/GameData/Solar/CollisionGroup.cs
- ./LibreLancer.Compatibility/GameData/Equipment/AbstractEquipment.cs
- ./LibreLancer.Compatibility/GameData/Equipment/EquipmentIni.cs
- ./LibreLancer.Compatibility/GameData/Equipment/Light.cs
- ./LibreLancer.Compatibility/GameData/Universe/Zone.cs
- ./LibreLancer.Compatibility/GameData/Universe/Band.cs
- ./LibreLancer.Compatibility/GameData/Universe/JumpReference.cs
- ./LibreLancer.Compatibility/GameData/Universe/Room.cs
- ./LibreLancer.Compatibility/GameData/Universe/UniverseIni.cs
- ./LibreLancer.Compatibility/GameData/Universe/Nebula.cs
- ./LibreLancer.Compatibility/GameData/Universe/Encounter.cs
- ./LibreLancer.Compatibility/GameData/Universe/StarSystem.cs
- ./LibreLancer.Compatibility/GameData/Universe/Field.cs
- ./LibreLancer.Compatibility/GameData/Universe/SystemObject.cs
- ./LibreLancer.Compatibility/GameData/Universe/NebulaLight.cs
- ./LibreLancer.Compatibility/GameData/Universe/ZoneReference.cs
- ./LibreLancer.Compatibility/GameData/Universe/AsteroidField.cs
- ./LibreLancer.Compatibility/GameData/Universe/EncounterParameter.cs
- ./LibreLancer.Compatibility/GameData/Universe/TexturePanels.cs
- ./LibreLancer.Compatibility/GameData/Universe/SystemPart.cs
- ./LibreLancer.Compatibility/GameData/Universe/LightSource.cs
- ./LibreLancer.Compatibility/GameData/Universe/Base.cs
- ./LibreLancer.Compatibility/GameData/Universe/NamedObject.cs
- ./LibreLancer.Compatibility/GameData/Universe/AsteroidBillboards.cs
- ./LibreLancer.Compatibility/GameData/Universe/UniverseElement.cs
- ./LibreLancer.Compatibility/GameData/Universe/DynamicAsteroids.cs
- ./LibreLancer.Compatibility/GameData/Universe/ExclusionZone.cs
- ./LibreLancer.Compatibility/GameData/Universe/LootableZone.cs
- ./LibreLancer.Compatibility/GameData/Cursor.cs
- ./LibreLancer.Compatibility/GameData/MouseShape.cs
- ./LibreLancer.Compatibility/GameData/Archetype.cs
- ./LibreLancer.Compatibility/Exceptions/FileVersionException.cs
- ./LibreLancer.Compatibility/Exceptions/FileException.cs
- ./LibreLancer.Compatibility/Exceptions/FileFormatException.cs
- ./LibreLancer.Compatibility/Exceptions/FileContentException.cs
- ./LibreLancer/Utf/AbstractConstruct.cs
- ./LibreLancer/Utf/Dfm/DfmPart.cs
- ./LibreLancer/Utf/Dfm/FaceGroup.cs
- ./LibreLancer/Utf/Dfm/DfmFile.cs
- ./LibreLancer/Utf/Dfm/DfmMesh.cs
- ./LibreLancer/Utf/Dfm/Bone.cs
- ./LibreLancer/Utf/Vms/VMeshData.cs
- ./LibreLancer/Utf/Vms/TMeshHeader.cs
- ./LibreLancer/Utf/Vms/VmsFile.cs
- ./LibreLancer/Utf/RevConstruct.cs
- ./LibreLancer/Utf/ConstructCollection.cs
- ./LibreLancer/Utf/Cmp/CmpFile.cs
- ./LibreLancer/Utf/Cmp/ModelFile.cs
- ./LibreLancer/Utf/Cmp/VMeshRef.cs
- ./LibreLancer/Utf/Cmp/RevoluteHardpointDefinition.cs
- ./LibreLancer/Utf/Cmp/Part.cs
- ./LibreLancer/Utf/Cmp/FixedHardpointDefinition.cs
- ./LibreLancer/Utf/Cmp/HardpointDefinition.cs
- ./LibreLancer/Utf/Mat/SphFile.cs
- ./LibreLancer/Utf/Mat/MatFile.cs
- ./LibreLancer/Utf/Mat/TxmFile.cs
- ./LibreLancer/Utf/Mat/TextureData.cs
- ./LibreLancer/Utf/Mat/Material.cs
- ./LibreLancer/Utf/FixConstruct.cs
- ./LibreLancer/Utf/Anm/Script.cs
- ./LibreLancer/Utf/Anm/Frame.cs
- ./LibreLancer/Utf/Anm/AnmFile.cs
- ./LibreLancer/Utf/Anm/Channel.cs
- ./LibreLancer/Utf/UtfFile.cs
- ./LibreLancer/Utf/SphereConstruct.cs
- ./LibreLancer/Utf/PrisConstruct.cs
- ./LibreLancer/Utf/LooseConstruct.cs
- ./LibreLancer/ConvertData.cs
- ./LibreLancer/ChaseCamera.cs
- ./LibreLancer/IDrawable.cs
- ./LibreLancer/ILibFile.cs
- ./LibreLancer/TextureShape.cs
- ./LibreLancer/CrcTool.cs
- ./Editor/SystemViewer/DebugCamera.cs
- ./LibreLancer.ImageLib/TGA.cs

**Comment by Giperionn** [comment]
Yes, you can use my code with MIT license

**Comment by gp-alex** [comment]
Sure, fine with me

**Comment by CallumDev** [comment]
![image](https://user-images.githubusercontent.com/10167247/47255633-eaea5a00-d4bb-11e8-88ab-67f66f60a448.png)
Have permission from Malte Rupprecht! Will keep this issue open for a while just in case anyone has issues

**Comment by rupprema** [comment]
Hi, I'm sorry, I wanted to comment sooner but somehow forgot.
I'm fine with relicensing my code contributions under MIT license.

**Comment by CallumDev** [comment]
Relicense is complete and issue has been left open long enough, closing :)
