### ISSUE TITLE
Material dc crashes if it's a single byte

### ISSUE THREAD

**Issue by CallumDev** [Librelancer/Librelancer#5]
Shown in submitted screenshot:
![devenv_2016-08-10_18-12-15](https://cloud.githubusercontent.com/assets/10167247/17559579/dbebb5e2-5f5d-11e6-91b0-178b631b8175.png)

From Freelancer Repack mod

**Comment by erenes** [comment]
How do you reproduce this error? I can't promise I will be able to solve it, but I'd like to take a look. 

On the other hand, if an Int32 is expected, the data should be 4 bytes so I wonder what the original intention could be here.

**Comment by CallumDev** [comment]
@erenes Looks like I uploaded the wrong screenshot, it's supposed to be n.ColorData being null for Dc. In that case an array of 4 floats (16 bytes) should be expected. You can reproduce by using a repacked version of Freelancer from a questionable source I can't link to :P

**Comment by erenes** [comment]
That might explain ;) 

I just installed Freelancer from CD and didn't see a crash, so I wonder if the data files are different or if I was just doing something different (flying around star systems)  :)

If you know which file gets this error I can give you the checksum of my file? If the 'repack' is corrupted it would be good to know right?

**Comment by CallumDev** [comment]
I couldn't actually find this mod, re-open if it's found.
