### ISSUE TITLE
About contributing

### ISSUE THREAD

**Issue by Regenhardt** [Librelancer/Librelancer#54]
I'd like to contribute somehow. Can I start with optimizing your C# code? like making things readonly where applicable and stuff.

Are there strict code conventions? I don't see an .editorconfig file, may I make one from the conventions I find in the code?

Tabs or spaces?

**Comment by CallumDev** [comment]
I'd avoid doing the `readonly` micro-optimisation in a lot of places. I find the keyword useful to mark things that should definitely not be able to be changed, and occasionally the semantics can mean you can end up with regressions as in this article: https://codeblog.jonskeet.uk/2014/07/16/micro-optimization-the-surprising-inefficiency-of-readonly-fields/ It also adds a bit of noise in commits.

For code conventions I've been attempting to stick with the default MonoDevelop policy, though that has changed a couple of times throughout the years. 4 spaces, though in practice a lot of files have somehow (despite my editor being set up for spaces) ended up mixed tabs and spaces.

**Comment by Regenhardt** [comment]
Wow, wasn't aware of the copying around, intuitively I was rather thinking the opposite. 

I'll start with an .editorconfig, that'll make most IDEs opening this project use 4 spaces. I'll also make the readonly rule silent, since my VS now tells me I have lots of errors because of different global settings. 

Then I'll look at issues and see what seems doable to me :D

**Comment by Regenhardt** [comment]
Made a PR #55

**Comment by Regenhardt** [comment]
Have you thought about upgrading to core? Real cross platform support and easier project handling. Not sure how much Windows APIs are fixed in the code though.

**Comment by Regenhardt** [comment]
And I don't know about ;omoDevelop, does it care about the VS version in the sln file? My VS always upgrades the VS version in the sln file, I always have to work around not commiting that. Would love to just throw it in.

**Comment by Regenhardt** [comment]
Btw the available rules are listed here: https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2019

Sorry for spamming a bit. I'm so hyped and editorconfig and .NET Core upgrade is what I'm currently doing at work so I have actual information about that on my hands right now.

**Comment by CallumDev** [comment]
Thanks for the rules link. At the moment I plan on sticking with netfx and mono as the toolchain behind it is very mature, and core toolsets are a bit difficult to work with on Linux distributions.

I'll see how the situation develops with the upcoming .NET 5 and plan a migration from there. 

I'll close this issue for now (I think it can still be commented on if needed) to help a bit with spam. I find discussions are best to be had on our Discord (see README) if you can use that platform
