### ISSUE TITLE
Not existing reference in project file

### ISSUE THREAD

**Issue by Regenhardt** [Librelancer/Librelancer#57]
https://github.com/Librelancer/Librelancer/blob/97902565f2ab752443bfbebb9ec46e3393dcac98/src/Editor/SystemViewer/SystemViewer.csproj#L53

Where is that supposed to go? Build works when removed.

**Comment by CallumDev** [comment]
Oh that's supposed to be a reference LibreLancer.Data.csproj, I guess
MSBuild goes by GUID a lot of the time will fix shortly
