### ISSUE TITLE
How to develop Librelancer ?

### ISSUE THREAD

**Issue by SashaRomanov** [Librelancer/Librelancer#74]
I know this is a simple question but i don't know how to start developing Librelancer or the best practice in doing so.
is there a UI editor for opengl games.
i come from unity and i'm new to this can some one help me understand ?

**Comment by Lazrius** [comment]
Librelancer is an open source re-implementation of the Freelancer engine. There is no 'editor' or anything of the like. To be perfectly honest, I'm not sure what the question actually is. I'm assuming that you're under the impression this is a 'general' game engine that can be used for a multitude of game types? If so, I'm afraid you'll be disappointing.

**Comment by SashaRomanov** [comment]
@Lazrius i thought i can modify the code of the game for my purposes but i don't know what engine do i use to start working with this game. i mean how can i change the graphics or add new functionalities.
I searched google and i found GLFW frame work to start working with such code.
but i could figure out how to implement a good frame work to modify the graphics and the logic ?

**Comment by CallumDev** [comment]
Hi,

If you're looking to do from-scratch games in C# I suggest looking into either [MonoGame](https://www.monogame.net/) or [OpenTK](https://github.com/opentk/opentk). Librelancer is not a suitable project for beginners and non-Freelancer modifications are out of scope.
