### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by BrosephJ** [Librelancer/Librelancer#79]
On Arch Linux, certain that I have all the prerequisite packages installed. Error on my end or bug in the build script? No idea how to debug this.
[CMakeOutput.log](https://github.com/Librelancer/Librelancer/files/5880449/CMakeOutput.log)
![librelancer_error](https://user-images.githubusercontent.com/5185864/105996449-31499e80-605f-11eb-8302-888cf9f0100f.png)

**Comment by CallumDev** [comment]
You need to clone with submodules, `git submodule update --init --recursive` should do it.

**Comment by BrosephJ** [comment]
I can read instructions I swear! :(

**Comment by CallumDev** [comment]
I've now updated the build scripts to clone submodules if they are forgotten, closing. Please re-open if there are any more compile bugs under Arch.
