### ISSUE TITLE
lancer.exe crashes on minimise when anti-aliasing enabled

### ISSUE THREAD

**Issue by JimJamJamie** [Librelancer/Librelancer#83]
**Description**

A reproducible crash is observed when minimising the main `lancer.exe` window.

**Environment**

- Windows 11 Pro x64 21H2 Build 22000.613
- Intel Core i5-5200 CPU
- 2x 8GB DDR3-1600 RAM - Recent Memtest86 PASS
- Intel HD Graphics 5500, driver version 20.19.15.5166
- WD Blue 3D 500 GB SATA SSD

**How to reproduce:**

- Launch librelancer from Launcher.exe, and wait until the main menu is loaded.
- Enable anti-aliasing in the Performance Options.
- Minimise the main window.
- The main window will then close and the following error is displayed:

> Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>    at LibreLancer.MultisampleTarget.BlitToScreen()
>    at LibreLancer.SystemRenderer.Draw()
>    at LibreLancer.LuaMenu.Draw(Double)
>    at LibreLancer.FreelancerGame.Draw(Double)
>    at LibreLancer.Game.Run()
>    at lancer.MainClass+<>c__DisplayClass0_0.<Main>b__0()
>    at LibreLancer.AppHandler.Run(System.Action, System.Action)
>    at lancer.MainClass.Main(System.String[])
> 
> [process exited with code 3221225477 (0xc0000005)]

**Comment by JimJamJamie** [comment]
An update to this: I tried the same actions on a completely different machine and also got a crash on minimise:

> GL Error: Invalid Framebuffer Operation
>    at LibreLancer.GL.ErrorCheck()
>    at LibreLancer.SystemRenderer.Draw()
>    at LibreLancer.LuaMenu.Draw(Double delta)
>    at LibreLancer.FreelancerGame.Draw(Double elapsed)
>    at LibreLancer.Game.Run()
>    at lancer.MainClass.<>c__DisplayClass0_0.<Main>b__0()
>    at LibreLancer.AppHandler.Run(Action action, Action onCrash)
> 
> Librelancer Version: ad316cb-git (20220930)

This was on a desktop machine this time, specs as follows:

AMD A10-8750B APU with onboard radeon R7 graphics
16 GB DDR3 RAM
500GB SATA SSD

**Comment by CallumDev** [comment]
Note to future self: Windows sets the window size to 0,0 when minimised - this does not happen on Linux
