### ISSUE TITLE
LancerEdit crashes when pressing "Play Audio" on non-audio stream

### ISSUE THREAD

**Issue by BC46** [Librelancer/Librelancer#88]
When pressing the "Play Audio" button on a `DDS` texture file for example, LancerEdit simply crashes without a warning. This isn't really the most user-friendly behavior since a user could press this button at any time by accident. Having to restart the application just for that is a bit too much of a hassle.

![image](https://user-images.githubusercontent.com/45081813/195979873-95334ed8-8a0b-4929-96c9-6fd7fba98aa3.png)

**Comment by CallumDev** [comment]
Fixed with #89
